= Recap

Thanks to your help Infinicorp was able to do the following: 

For directly connected systems: +

* Review the internet connected RHEL 9.7 system to identify if there are any common vulnerabilities and exposures (CVEs) that are critical or important which need to be addressed.
* Evaluate the internet connected RHEL 9.7 system for compliance to the Center for Internet Security (CIS) Level 1 Server policy and identify what needs to be updated/changed to get the system into compliance.

For Satellite connected systems: +

* Review the Satellite connected 10.1 host to see if there are any recommendations to improve the reliability, performance, or security of the host.
* Review the Satellite connected 10.1 host to see if there are any common vulnerabilities and exposures (CVEs) that are critical which need to be addressed.

Great job - thank you for all of your assistance, and we hope that you learned some things along the way.

= Now, a word from the product team.

During the course of this lab, the Red Hat Lightspeed and Satellite teams wanted to highlight a few different things.

In modules 2 (Red Hat Lightspeed via the Hybrid Cloud Console - Evaluate and remediate CVEs) and 3 (Red Hat Lightspeed via the Hybrid Cloud Console - Evaluate regulatory compliance) we highlighted services and capabilities of Red Hat Lightspeed on the Hybrid Cloud Console.   

These two services are not generally available as part of the Red Hat Lightspeed in Satellite capabilities, but they are services that are in technology preview (vulnerability) or are being considered for inclusion for a future release (compliance).  +
The Red Hat Lightspeed team wanted you to get a feel for the capabilities and how they work.

In module 4 (Advisor recommendations in Satellite) you experienced the Red Hat Lightspeed advisor capability inside of Red Hat Satellite. + 
Advisor has been available in Satellite since approximately Satellite 6.4, but with Lightspeed in Satellite this capability is disconnected and no longer requires a connection to the internet. + 
The user interface for Red Hat Lightspeed in Satellite is also refreshed and looks and feels more like what is on the Hybrid Cloud Console. 

In module 5 you experienced the technology preview vulnerability service. + 
This has limited capabilities today, but you got to explore what this may look like in the future in module 2. + 
Remediation is notably missing while in technology preview, but you can get a feel for where we are going with this service.

Red Hat Lightspeed in Satellite consists of a series of podman containers. + 
These containers are included with the Satellite ISO image or can be downloaded from the image registry.  +
Enabling Red Hat Lightspeed in Satellite does disable *ALL* connectivity with the Hybrid Cloud Console. +
It also removed what are now irrelevant menu items inside of the Satellite user interface. +
The Red Hat Lightspeed analysis happens right on the Satellite server and no information leaves the Satellite.   

Updates to Red Hat Lightspeed in Satellite will be delivered in future Satellite releases. +
We encourage you to use Red Hat Lightspeed advisor in Satellite and share your feedback with the Red Hat Lightspeed team by emailing us at Lightspeed@redhat.com.
